//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Dicionario.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.Dicionario.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap geracaoCodigo {
            get {
                object obj = ResourceManager.GetObject("geracaoCodigo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icoTnf {
            get {
                object obj = ResourceManager.GetObject("icoTnf", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MigrationWizard {
            get {
                object obj = ResourceManager.GetObject("MigrationWizard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicações.
        /// </summary>
        internal static string ResAplicacoes {
            get {
                return ResourceManager.GetString("ResAplicacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiado para a &quot;Área de transferência&quot;.
        /// </summary>
        internal static string ResCopiadoAreaTransferencia {
            get {
                return ResourceManager.GetString("ResCopiadoAreaTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonte de dados não corresponde à tabela de Dicionário..
        /// </summary>
        internal static string ResDataSourceNaoDicionario {
            get {
                return ResourceManager.GetString("ResDataSourceNaoDicionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string ResDescricao {
            get {
                return ResourceManager.GetString("ResDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geração de código.
        /// </summary>
        internal static string ResGeracaoCodigo {
            get {
                return ResourceManager.GetString("ResGeracaoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar DataProps do(s) campo(s) selecionado(s).
        /// </summary>
        internal static string ResGerarDataPropsCampos {
            get {
                return ResourceManager.GetString("ResGerarDataPropsCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar ParamsProc do(s) campo(s) selecionado(s).
        /// </summary>
        internal static string ResGerarParamsProc {
            get {
                return ResourceManager.GetString("ResGerarParamsProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string ResInformacao {
            get {
                return ResourceManager.GetString("ResInformacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a sigla do módulo do sistema (Ex: Edu):.
        /// </summary>
        internal static string ResInformeSiglaModulo {
            get {
                return ResourceManager.GetString("ResInformeSiglaModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** NÃO EXISTE NA GDIC!!! ***.
        /// </summary>
        internal static string ResNaoExisteDicionario {
            get {
                return ResourceManager.GetString("ResNaoExisteDicionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório.
        /// </summary>
        internal static string ResObrigatorio {
            get {
                return ResourceManager.GetString("ResObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisão.
        /// </summary>
        internal static string ResPrecisao {
            get {
                return ResourceManager.GetString("ResPrecisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do módulo.
        /// </summary>
        internal static string ResSiglaModulo {
            get {
                return ResourceManager.GetString("ResSiglaModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNF - Criar mapeamento de entidade.
        /// </summary>
        internal static string StrTnfCreateEntityMap {
            get {
                return ResourceManager.GetString("StrTnfCreateEntityMap", resourceCulture);
            }
        }
    }
}
